# 匹配main分支
main:
  # 触发事件为push事件
  push:
    # 这里是阶段任务示例，可配置任意多个阶段，这里以一个阶段为例
    - name: '测试'
      stages:
        # 使用流水线输出你的构建配置数据
        - name: echo your build data
          script: echo ${CNB_BUILD_USER} 通过 ${CNB_BRANCH} 分支触发了 ${CNB_EVENT} 事件
