version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ufun-website
    ports:
      - '80:80'
    restart: always
    networks:
      - app-network
    volumes:
      - /www/docker-apps/ufun-website/data:/app/data
      - /www/docker-apps/ufun-website/config/nginx.conf:/etc/nginx/nginx.conf

networks:
  app-network:
    driver: bridge
