version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-interactive-app
    ports:
      - '80:80'
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
